config/routes.rb
Rails.application.routes.draw do
  # Beers
  resources :bottles do
    collection { get :drink }
  end

  # Other resources
  resources :beers, :breweries

  # This is a route handled by OmniAuth, give it a nice name
  direct :sign_in do
    "/auth/google_oauth2"
  end
  get "/auth/:provider/callback" => "sessions#create"

  # The rest of our routes for authentication
  get "/auth/failure" => "sessions#failure"
  post "/auth/sign_out" => "sessions#destroy", :as => :sign_out

  # User and settings management
  post "/auth/delete" => "sessions#delete", :as => :user_delete
  get "/auth/settings" => "sessions#show", :as => :user_settings

  # Static pages
  get "/about" => "static#about"
  get "/privacy" => "static#privacy"
  root "static#index"

  # Error pages
  get "/404" => "errors#not_found"
  get "/422" => "errors#unprocessable_entity"
  get "/500" => "errors#internal_server_error"
end

app/models/bottle.rb
# Bottle is the representation of a single bottle of a beer, owned by a given
# user.
#
# @!attribute name
#   An optional user-friendly name for this bottle
#
#   If not specified, we just identify the bottle by its bottling date.
#
#   @return [String] the bottle's name
# @!attribute beer
#   The beer that this bottle contains
#
#   @return [Beer] the beer that this bottle contains
# @!attribute rule
#   The aging rule for this bottle
#
#   @return [Rule] the rule for aging this bottle
# @!attribute user
#   The user who owns this bottle
#
#   This is fetched via the owner of the aging rule, and is guaranteed to always
#   be present.
#
#   @return [User] the user who owns this bottle
# @!attribute bottled_on
#   The date on which this beer was bottled
#
#   @raise [ValidationError] if `bottled_on` is absent (`validates :presence`)
#   @return [Date] the bottling date
# @!attribute window_start
#   The start of the drinking window for this bottle
#
#   @return [Date] the start of the drinking window
# @!attribute window_end
#   The end of the drinking window for this bottle
#
#   @return [Date] the end of the drinking window
# @!attribute drunk
#   If true, this bottle has been drunk
#
#   @raise [ValidationError] if `drunk` is absent (`validates :presence`)
#   @return [Boolean] the drunk status
# @!attribute drunk_on
#   The date on which this bottle was drunk
#
#   @return [Date] the drinking date
# @!attribute description
#   An optional description of this bottle
#
#   @return [String] the description of the bottle
class Bottle < ApplicationRecord
  belongs_to :beer
  belongs_to :rule
  has_one :user, through: :rule

  validates :rule, presence: true
  validates :beer, presence: true
  validates :bottled_on, presence: true

  # The earliest date on which this beer should be drunk
  #
  # This returns the `bottled_on` date plus the minimum number of months as
  # specified in the aging rule. If `past` is true, then this date can be in the
  # past, otherwise it will be clamped to "today" if it would otherwise be in
  # the past.
  #
  # @param past [Boolean] if true, allow dates in the past
  # @return [Date] earliest possible drinking date
  def window_earliest(past: false)
    date = bottled_on + rule.min_months.months
    date = Time.zone.today if !past && date < Time.zone.today

    date
  end

  # The latest date on which this beer should be drunk
  #
  # This returns the `bottled_on` date plus the maximum number of months as
  # specified in the aging rule.
  #
  # @return [Date] latest possible drinking date
  def window_latest
    bottled_on + rule.max_months.months
  end

  # Reset the drinking window for this beer to its largest possible value
  #
  # @return [void]
  def reset_window
    self.window_start = window_earliest
    self.window_end = window_latest
    save
  end
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bottle, only: %i[show edit update destroy]

  def index
    @bottles = current_user.bottles.all
  end

  def show
  end

  def new
    @bottle = current_user.bottles.new
  end

  def edit
  end

  def create
    @bottle = current_user.bottles.new(bottle_params)

    if @bottle.save
      redirect_to bottle_url(@bottle), notice: I18n.t(".success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bottle.update(bottle_params)
      redirect_to bottle_url(@bottle), notice: I18n.t(".success")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bottle.destroy!
    redirect_to bottles_url, notice: I18n.t(".success")
  end

  def drink
  end

  private

  def set_bottle
    @bottle = Bottle.find(params[:id])
  end

  def bottle_params
    params.require(:bottle).permit(
      :name,
      :rule_id,
      :beer_id,
      :bottled_on,
      :description,
      :drunk,
      :drunk_on
    )
  end
end

app/views/bottles/_bottle.html.haml
%div{id: dom_id(bottle)}
  %p
    %strong Name:
    = bottle.name
  %p
    %strong Rule:
    = bottle.rule.name
  %p
    %strong Beer:
    = bottle.beer.name
  %p
    %strong Bottled on:
    = bottle.bottled_on
  %p
    %strong Description:
    = bottle.description
  %p
    %strong Drunk?
    = bottle.drunk
  %p
    %strong Drunk on:
    = bottle.drunk_on
  %p
    %strong Drink window start:
    = bottle.window_start
  %p
    %strong Drink window end:
    = bottle.window_end
  %p
    %small
      Created:
      = beer.created_at
      | Updated:
      = beer.updated_at

app/views/bottles/_form.html.haml
= form_with(model: bottle) do |form|
  .mb-3
    = form.label :name, class: 'form-label'
    = form.text_field :name, class: "form-control #{validate_class(bottle, :name)}"
    = validate_error bottle, :name
  .mb-3
    = form.label :rule_id, class: 'form-label'
    = form.select :rule_id, current_user.rules.collect { |r| [ r.name, r.id ] }, {}, { class: "form-select #{validate_class(bottle, :rule)}" }
    = validate_error bottle, :rule
  .mb-3
    = form.label :beer_id, class: 'form-label'
    = form.select :beer_id, Beer.all.collect { |b| [ b.name, b.id ] }, {}, { class: "form-select #{validate_class(bottle, :beer)}" }
    = validate_error bottle, :beer
  .mb-3
    = form.label :bottled_on, class: 'form-label'
    = form.date_field :bottled_on, class: "form-control #{validate_class(bottle, :bottled_on)}"
    = validate_error bottle, :bottled_on
  .mb-3
    = form.label :description, class: 'form-label'
    = form.text_field :description, class: "form-control #{validate_class(bottle, :description)}"
    = validate_error bottle, :description
  .mb-3
    = form.check_box :drunk, class: "form-check-input #{validate_class(bottle, :drunk)}"
    = form.label :drunk, class: 'form-check-label'
    = validate_error bottle, :drunk
  .mb-3
    = form.label :drunk_on, class: 'form-label'
    = form.date_field :drunk_on, class: "form-control #{validate_class(bottle, :drunk_on)}"
    = validate_error bottle, :drunk_on
  = form.submit class: 'btn btn-primary'

app/views/bottles/drink.html.haml
%h1 Beers#dashboard
%p Find me in app/views/beers/dashboard.html.erb

app/views/bottles/edit.html.haml
%h1 Editing Bottle

= render "form", bottle: @bottle

%div
  = link_to "Show this bottle", @bottle
  = link_to "Back to cellar", bottles_path

app/views/bottles/index.html.haml
%h1 Your Cellar

#bottles
  - @bottles.each do |bottle|
    = render bottle
    %p= link_to "Show this bottle", bottle

%p= link_to "New bottle", new_bottle_path

app/views/bottles/new.html.haml
%h1 New Bottle

= render "form", bottle: @bottle

%br/

%div
  = link_to "Back to bottles", bottles_path

app/views/bottles/show.html.haml
= render @bottle

%div
  = link_to "Edit this bottle", edit_bottle_path(@bottle)
  = link_to "Back to cellar", bottles_path

  = button_to "Delete this bottle", @bottle, method: :delete