config/routes.rb
Rails.application.routes.draw do
  # Beers
  resources :bottles do
    collection { get :drink }
  end

  # Other resources
  resources :beers, :breweries

  # This is a route handled by OmniAuth, give it a nice name
  direct :sign_in do
    "/auth/google_oauth2"
  end
  get "/auth/:provider/callback" => "sessions#create"

  # The rest of our routes for authentication
  get "/auth/failure" => "sessions#failure"
  post "/auth/sign_out" => "sessions#destroy", :as => :sign_out

  # User and settings management
  post "/auth/delete" => "sessions#delete", :as => :user_delete
  get "/auth/settings" => "sessions#show", :as => :user_settings

  # Static pages
  get "/about" => "static#about"
  get "/privacy" => "static#privacy"
  root "static#index"

  # Error pages
  get "/404" => "errors#not_found"
  get "/422" => "errors#unprocessable_entity"
  get "/500" => "errors#internal_server_error"
end

app/models/brewery.rb
# Brewery is the record for a brewery, to which many beers belong.
#
# @!attribute name
#   The brewery's name
#
#   @raise [ValidationError] if `name` is absent (`validates :presence`)
#   @return [String] the brewery's name
# @!attribute beers
#   A list of beers belonging to this brewery
#
#   @return [ActiveRecord::Relation] this brewery's beers
class Brewery < ApplicationRecord
  has_many :beers, dependent: :nullify

  validates :name, presence: true
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_brewery, only: %i[show edit update destroy]

  def index
    @breweries = Brewery.all
  end

  def show
  end

  def new
    @brewery = Brewery.new
  end

  def edit
  end

  def create
    @brewery = Brewery.new(beer_params)

    if @brewery.save
      redirect_to brewery_url(@brewery), notice: I18n.t(".success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @brewery.update(brewery_params)
      redirect_to brewery_url(@brewery), notice: I18n.t(".success")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @brewery.destroy!
    redirect_to brewery_url, notice: I18n.t(".success")
  end

  private

  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  def brewery_params
    params.require(:brewery).permit(:name)
  end
end

app/views/breweries/_brewery.html.haml
%div{id: dom_id(brewery)}
  %p
    %strong Name:
    = brewery.name
  %p
    %small
      Created:
      = brewery.created_at
      | Updated:
      = brewery.updated_at

app/views/breweries/_form.html.haml
= form_with(model: brewery) do |form|
  .mb-3
    = form.label :name, class: 'form-label'
    = form.text_field :name, class: "form-control #{validate_class(brewery, :name)}"
    = validate_error brewery, :name
  = form.submit class: 'btn btn-primary'

app/views/breweries/edit.html.haml
%h1 Editing Brewery

= render "form", brewery: @brewery

%div
  = link_to "Show this brewery", @brewery
  = link_to "Back to breweries", breweries_path

app/views/breweries/index.html.haml
%h1 Breweries

#breweries
  - @breweries.each do |brewery|
    = render brewery
    %p= link_to "Show this brewery", brewery

%p= link_to "New brewery", new_brewery_path

app/views/breweries/new.html.haml
%h1 New Brewery

= render "form", brewery: @brewery

%br/

%div
  = link_to "Back to breweries", breweries_path

app/views/breweries/show.html.haml
= render @brewery

%div
  = link_to "Edit this brewery", edit_brewery_path(@brewery)
  = link_to "Back to breweries", breweries_path

  = button_to "Delete this brewery", @brewery, method: :delete