config/routes.rb
Rails.application.routes.draw do
  # Beers
  resources :bottles do
    collection { get :drink }
  end

  # Other resources
  resources :beers, :breweries

  # This is a route handled by OmniAuth, give it a nice name
  direct :sign_in do
    "/auth/google_oauth2"
  end
  get "/auth/:provider/callback" => "sessions#create"

  # The rest of our routes for authentication
  get "/auth/failure" => "sessions#failure"
  post "/auth/sign_out" => "sessions#destroy", :as => :sign_out

  # User and settings management
  post "/auth/delete" => "sessions#delete", :as => :user_delete
  get "/auth/settings" => "sessions#show", :as => :user_settings

  # Static pages
  get "/about" => "static#about"
  get "/privacy" => "static#privacy"
  root "static#index"

  # Error pages
  get "/404" => "errors#not_found"
  get "/422" => "errors#unprocessable_entity"
  get "/500" => "errors#internal_server_error"
end

app/models/beer.rb
# Beer is the representation of a single product from a brewery, which could (at
# least in theory) be brewed multiple times.
#
# @!attribute name
#   The name of this beer
#
#   @raise [ValidationError] if `name` is absent (`validates :presence`)
#   @return [String] the beer's name
# @!attribute brewery
#   The brewery that brewed this beer
#
#   Note that we don't have support for collaboration brews (sorry, this isn't
#   Untappd). You'll have to pick a "primary" brewery.
#
#   @return [Brewery] the brewery that brewed this beer
# @!attribute disambiguation
#   An optional string to distinguish similar beers
#
#   Inspired by MusicBrainz, if this is set it will be shown in the UI in small,
#   grey font whenever the beer is shown to distinguish multiple beers with very
#   similar names.
#
#   @return [String] the beer's disambiguation string
# @!attribute description
#   An optional description of this beer
#
#   @return [String] the beer's description
class Beer < ApplicationRecord
  belongs_to :brewery

  validates :name, presence: true
  validates :beer, presence: true

  # Update the drinking windows for all bottles of this beer.
  #
  # Note that this will _erase_ the drinking windows for any bottles that have
  # them already set, recomputing all of them according to the drinking-window
  # algorithm.
  #
  # The algorithm evenly divides the extant bottles of this beer over the entire
  # aging period of each bottle.
  #
  # @param [User] user the user for whom to update drinking windows
  # @return [void]
  def update_windows(user)
    # Get the list of the user's bottles of this beer
    bottles = user.bottles.where(beer: self, drunk: false)
    return if bottles.empty?

    # Set the window of every bottle to the largest possible
    bottles.each(&:reset_window)

    # Get the lowest window_start date to start off the algorithm
    date = bottles.map(&:window_start).min
    active = active_bottles(bottles, date)

    # Okay, we're off, start the actual algorithm
    until active.empty?
      # Get the new list
      next_date = next_active_change(bottles, date)
      next_active = active_bottles(bottles, next_date)

      # Divide the time period between this date and the next date into an equal
      # number of parts
      time_slice = (next_date - date) / active.count

      # Assign the active bottles to subdivisions, leaving the start of the
      # first bottle and the end of the last bottle as they were
      active.each_with_index do |b, i|
        b.window_start = date if i != 0

        date += time_slice
        b.window_end = date if i != active.count - 1
        b.save
      end

      active = next_active
    end

    fix_overlap(bottles)
  end

  private

  # Get the bottles that are "active" at the given date
  #
  # From the given array of bottles, return those whose window includes the
  # given date. Return them sorted, first by their window_start, and then by
  # their botttled-on date.
  #
  # @param bottles [Array<Bottle>] the list of bottles to check
  # @param date [Date] the date for which to calculate
  # @return [Array<Bottle>] the bottles active at that date
  def active_bottles(bottles, date)
    bottles
      .select { |b| b.window_start <= date && b.window_end > date }
      .sort_by { |b| [b.window_start, b.bottled_on] }
  end

  # The next time the "active" list changes after the given date
  #
  # The next change in the active bottles list happens either when a bottle
  # leaves the list because it's out of the window, or when a new bottle enters
  # the list because we hit the start of its window. Find that date.
  #
  # @param bottles [Array<Bottle>] the list of all bottles to check
  # @param date [Date] the date after which to find the next change
  # @return [Date] the date of the next change in the active list
  def next_active_change(bottles, date)
    ret = Date.new(3000, 1, 1)

    bottles.each do |b|
      ret = b.window_start if b.window_start > date && b.window_start < ret
      ret = b.window_end if b.window_end > date && b.window_end < ret
    end

    ret
  end

  # Fix windows that overlap by one day
  #
  # This code creates drinking windows that overlap by a single day (where the
  # last day of one window is the first day of the following window). Fix that
  # here by adjusting `window_end`.
  #
  # @return [void]
  def fix_overlap(bottles)
    bottles.each_with_index do |b, i|
      if i == bottles.count - 1 || b.window_end == bottles[i + 1].window_start
        b.window_end -= 1.day
        b.save
      end
    end
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_beer, only: %i[show edit update destroy]

  def index
    @beers = Beer.all
  end

  def show
  end

  def new
    @beer = Beer.new
  end

  def edit
  end

  def create
    @beer = Beer.new(beer_params)

    if @beer.save
      redirect_to beer_url(@beer), notice: I18n.t(".success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @beer.update(beer_params)
      redirect_to beer_url(@beer), notice: I18n.t(".success")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @beer.destroy!
    redirect_to beer_url, notice: I18n.t(".success")
  end

  private

  def set_beer
    @beer = Beer.find(params[:id])
  end

  def beer_params
    params.require(:beer).permit(
      :name,
      :brewery_id,
      :disambiguation,
      :description
    )
  end
end

app/views/beers/_beer.html.haml
%div{id: dom_id(beer)}
  %p
    %strong Name:
    = beer.name
  %p
    %strong Brewery:
    = beer.brewery.name
  %p
    %strong Disambiguation:
    = beer.disambiguation
  %p
    %strong Description:
    = beer.description
  %p
    %small
      Created:
      = beer.created_at
      | Updated:
      = beer.updated_at

app/views/beers/_form.html.haml
= form_with(model: beer) do |form|
  .mb-3
    = form.label :name, class: 'form-label'
    = form.text_field :name, class: "form-control #{validate_class(beer, :name)}"
    = validate_error beer, :name
  .mb-3
    = form.label :brewery_id, class: 'form-label'
    = form.select :brewery_id, Brewery.all.collect { |b| [ b.name, b.id ] }, {}, { class: "form-select #{validate_class(beer, :brewery)}" }
    = validate_error beer, :brewery
  .mb-3
    = form.label :disambiguation, class: 'form-label'
    = form.text_field :disambiguation, class: "form-control #{validate_class(beer, :disambiguation)}"
    = validate_error beer, :disambiguation
  .mb-3
    = form.label :description, class: 'form-label'
    = form.text_field :description, class: "form-control #{validate_class(beer, :description)}"
    = validate_error beer, :description
  = form.submit class: 'btn btn-primary'

app/views/beers/edit.html.haml
%h1 Editing Beer

= render "form", beer: @beer

%div
  = link_to "Show this beer", @beer
  = link_to "Back to beers", beers_path

app/views/beers/index.html.haml
%h1 Beers

#beers
  - @beers.each do |beer|
    = render beer
    %p= link_to "Show this beer", beer

%p= link_to "New beer", new_beer_path

app/views/beers/new.html.haml
%h1 New Beer

= render "form", beer: @beer

%br/

%div
  = link_to "Back to beers", beers_path

app/views/beers/show.html.haml
= render @beer

%div
  = link_to "Edit this beer", edit_beer_path(@beer)
  = link_to "Back to beers", beers_path

  = button_to "Delete this beer", @beer, method: :delete