config/routes.rb
Rails.application.routes.draw do
  # Beers
  resources :bottles do
    collection { get :drink }
  end

  # Other resources
  resources :beers, :breweries

  # This is a route handled by OmniAuth, give it a nice name
  direct :sign_in do
    "/auth/google_oauth2"
  end
  get "/auth/:provider/callback" => "sessions#create"

  # The rest of our routes for authentication
  get "/auth/failure" => "sessions#failure"
  post "/auth/sign_out" => "sessions#destroy", :as => :sign_out

  # User and settings management
  post "/auth/delete" => "sessions#delete", :as => :user_delete
  get "/auth/settings" => "sessions#show", :as => :user_settings

  # Static pages
  get "/about" => "static#about"
  get "/privacy" => "static#privacy"
  root "static#index"

  # Error pages
  get "/404" => "errors#not_found"
  get "/422" => "errors#unprocessable_entity"
  get "/500" => "errors#internal_server_error"
end

app/views/layouts/_alerts.html.haml
.container
  - flash.each do |type, msg|
    %div{ class: 'alert alert-dismissible fade show ' + flash_map[type], role: 'alert' }
      = msg
      %button.btn-close{ type: 'button', data: { bs_dismiss: 'alert' }, aria: { label: t('common.close_label') } }

app/views/layouts/_footer.html.haml
%footer.mt-5.py-4.bg-light.text-muted.text-center.small= t('.credit_md', this_year: Time.zone.now.year)

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-3.border-bottom
  .container-fluid
    = link_to root_path, class: "navbar-brand" do
      %img{src: "/favicon-32x32.png", width: "32", height: "32"}/
      = t('common.title')

    %button.navbar-toggler{
      type: "button",
      data: { bs_toggle: "collapse", bs_target: "#navbar-nav" },
      aria: {
        controls: "navbar-nav",
        expanded: "false",
        label: "Toggle navigation"
      }
    }
      %span.navbar-toggler-icon/

    .collapse.navbar-collapse#navbar-nav
      %ul.navbar-nav.me-auto
        - if user_signed_in?
          %li.nav-item
            = link_to t('nav.dashboard'), drink_bottles_path, class: 'nav-link'
          %li.nav-item
            = link_to t('nav.cellar'), bottles_path, class: 'nav-link'
        %li.nav-item.dropdown
          = link_to "Beer Library", '#', id: 'navbar-library', class: 'nav-link dropdown-toggle', role: 'button', data: { bs_toggle: 'dropdown' }, aria: { expanded: 'false' }
          %ul.dropdown-menu{aria: { labelledby: "navbar-library" }}
            %li= link_to "Breweries", breweries_path, class: "dropdown-item"
            %li= link_to "Beers", beers_path, class: "dropdown-item"

      - if user_signed_in?
        %ul.navbar-nav
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle#navbar-user{
              href: "#",
              data: { bs_toggle: "dropdown" },
              aria: { expanded: "false" }
            }
              %img.rounded-circle{
                src: current_user.image,
                width: "32",
                height: "32"
              }/

            %ul.dropdown-menu.dropdown-menu-end{
              aria: { labelledby: "navbar-user" }
            }
              %li
                = link_to t("nav.settings"), user_settings_path, class: "dropdown-item"
              %li
                = link_to t("nav.delete_account"), user_delete_path, class: "dropdown-item", data: { bs_toggle: "modal", bs_target: "#deleteModal" }
              %li
                %hr.dropdown-divider/
              %li
                = link_to t("nav.sign_out"), sign_out_path, method: :post, class: "dropdown-item"
      - else
        = link_to sign_in_path, method: :post, class: 'btn btn-outline-success' do
          = svg_tag 'google'
          = t('nav.sign_in')

- if user_signed_in?
  .modal.fade#deleteModal{
    tabindex: "-1",
    aria: { labelledby: "deleteModalLabel" }
  }
    .modal-dialog
      .modal-content
        .modal-header
          %h5.modal-title#deleteModalLabel= t("nav.delete_title")
          %button.btn-close{
            type: "button",
            data: { bs_dismiss: "modal" },
            aria: { label: t("common.close_label") }
          }

        .modal-body
          %p= t("nav.delete_text_md")
        .modal-footer
          %button.btn.btn-secondary{data: { bs_dismiss: "modal" }}
            = t("common.cancel_label")
          = form_with url: user_delete_path, method: :post do |f|
            = f.submit t('nav.delete_button'), class: 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= t("common.title")

    %meta{charset: "utf-8"}/
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}/
    = csrf_meta_tag
    = csp_meta_tag

    %link{
      rel: "stylesheet",
      href: "https://cdn.jsdelivr.net/npm/bootswatch@5.3.2/dist/journal/bootstrap.min.css",
      integrity: "sha256-0aRkQgTM21aUzcuBdnbwxGcGGWF1YxVc1QNkPzWL1+E=",
      crossorigin: "anonymous"
    }/

    = stylesheet_link_tag 'application'

    = javascript_importmap_tags

    = render 'layouts/favicons'

  %body
    = render 'layouts/svg'
    = render 'layouts/nav'
    = render 'layouts/alerts'

    = yield

    = render 'layouts/footer'

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lambic Cellar: Error</title>
    <meta charset="utf-8" />
    <meta content="width=device-width,initial-scale=1" name="viewport" />

    <link
      crossorigin="anonymous"
      href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/journal/bootstrap.min.css"
      integrity="sha256-Ont0XKIPs4G8F5vswFwCkN5t7KOSd8L8ifYhadEfEvk"
      rel="stylesheet"
    />

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
    <link rel="manifest" href="/site.webmanifest" />
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
    <meta name="msapplication-TileColor" content="#ffc40d" />
    <meta name="theme-color" content="#ffffff" />
  </head>
  <body>
    <div class="container mb-5" style="text-align: center">
      <img
        class="my-4"
        src="/android-chrome-512x512.png"
        width="512"
        height="512"
        alt="Lambic Cellar logo"
      />
      <h1 class="display-5 fw-bold"><%= header %></h1>
      <div class="col-lg-6 mx-auto"><%= explanation %></div>
    </div>
  </body>
</html>